import type { DemoEvent } from "@/components/event/event-card";

/** Placeholder events until NestJS API is wired (Phase 2). */
export const DEMO_EVENTS: DemoEvent[] = [
  {
    id: "boardgame-night",
    title: "Board Game Night: Strategy & Snacks",
    category: "Board Game",
    location: "Jakarta Selatan",
    dateLabel: "Sab, 28 Mar · 19:00",
    quotaLabel: "12 / 20 kursi",
    priceLabel: "Gratis",
    isFree: true,
    coverGradient: "from-blue-500 to-indigo-600",
  },
  {
    id: "tech-meetup",
    title: "Tech Meetup: Next.js & Product Design",
    category: "Tech",
    location: "Jakarta Pusat",
    dateLabel: "Rab, 1 Apr · 18:30",
    quotaLabel: "48 / 60 kursi",
    priceLabel: "Rp 50rb",
    isFree: false,
    coverGradient: "from-violet-500 to-purple-700",
  },
  {
    id: "kopi-santai",
    title: "Kopi Santai & Networking Komunitas",
    category: "Kuliner",
    location: "Bandung",
    dateLabel: "Min, 5 Apr · 10:00",
    quotaLabel: "8 / 15 kursi",
    priceLabel: "Gratis",
    isFree: true,
    coverGradient: "from-amber-500 to-orange-600",
  },
  {
    id: "futsal-sore",
    title: "Futsal Sore Bareng Komunitas",
    category: "Olahraga",
    location: "Depok",
    dateLabel: "Jum, 3 Apr · 17:00",
    quotaLabel: "14 / 16 kursi",
    priceLabel: "Rp 35rb",
    isFree: false,
    coverGradient: "from-emerald-500 to-teal-700",
  },
  {
    id: "live-sketch",
    title: "Live Sketching di Taman Kota",
    category: "Seni",
    location: "Yogyakarta",
    dateLabel: "Sab, 11 Apr · 15:00",
    quotaLabel: "20 / 25 kursi",
    priceLabel: "Gratis",
    isFree: true,
    coverGradient: "from-rose-500 to-pink-600",
  },
  {
    id: "open-mic",
    title: "Open Mic Musik Akustik",
    category: "Musik",
    location: "Surabaya",
    dateLabel: "Sab, 18 Apr · 20:00",
    quotaLabel: "30 / 40 kursi",
    priceLabel: "Rp 25rb",
    isFree: false,
    coverGradient: "from-cyan-500 to-blue-700",
  },
];

export const CATEGORIES = [
  "Semua",
  "Board Game",
  "Tech",
  "Kuliner",
  "Olahraga",
  "Seni",
  "Musik",
] as const;
